import type { QuizSet } from './types';

const quiz: QuizSet = {
  slug: '25-files-and-directories',
  chapterNumber: 25,
  title: 'Files and Directories',
  description: 'inode, fd 사슬, offset 트레이스, strace cat, fsync/rename, link count — 표·코드 빵꾸 다수.',
  questions: [
    // ═══════════════════════════════════════════════════════════════════
    // True / False
    // ═══════════════════════════════════════════════════════════════════
    {
      id: 'ch25-tf-1',
      type: 'true-false',
      prompt: 'OS 입장에서 파일은 .txt, .jpg 같은 확장자의 의미와 무관하게 연속된 byte stream(선형 배열)일 뿐이다.',
      answer: true,
      explanation: '확장자 해석은 응용 프로그램의 몫. 커널에게 파일은 byte 배열 + inode 다.',
    },
    {
      id: 'ch25-tf-2',
      type: 'true-false',
      prompt: 'inode number 는 시스템 전체에서 유일한 값이다.',
      answer: false,
      explanation: '단일 파일 시스템(파티션) 내부에서만 유일. 다른 파티션에는 같은 번호의 다른 파일이 있을 수 있다 — hard link 가 파일 시스템을 못 넘는 이유.',
    },
    {
      id: 'ch25-tf-3',
      type: 'true-false',
      prompt: 'Linux 에서 디렉터리도 파일이며, 그 내용은 (파일 이름, inode 번호) 쌍들의 리스트다.',
      answer: true,
      explanation: '디렉터리 = directory entry 들의 리스트를 data 로 갖는 특수한 파일. 그래서 . 과 .. 도 entry 로 존재한다.',
    },
    {
      id: 'ch25-tf-4',
      type: 'true-false',
      prompt: 'lseek() 를 호출하면 디스크 헤드가 해당 위치로 이동(seek)한다.',
      answer: false,
      explanation: 'lseek 는 open file table entry 의 offset 정수만 바꾼다 — disk I/O 없음. 실제 디스크 접근은 다음 read/write 때.',
    },
    {
      id: 'ch25-tf-5',
      type: 'true-false',
      prompt: '같은 파일을 두 번 open 하면 두 fd 는 같은 open file table entry 를 가리키므로 offset 을 공유한다.',
      answer: false,
      explanation: 'open 을 따로 하면 entry 도 따로 생긴다 — offset 독립. entry 를 공유하는 것은 fork 상속과 dup 의 경우.',
    },
    {
      id: 'ch25-tf-6',
      type: 'true-false',
      prompt: 'fork() 후 자식이 lseek 로 offset 을 옮기면, 부모가 보는 offset 도 함께 바뀐다.',
      answer: true,
      explanation: '자식은 fd table 을 상속받고 같은 open file entry 를 공유(ref 증가)하므로 offset 도 공유 — fork-seek 예제에서 둘 다 10.',
    },
    {
      id: 'ch25-tf-7',
      type: 'true-false',
      prompt: 'write() 가 반환되었다면 데이터는 이미 디스크에 안전하게 기록된 것이다.',
      answer: false,
      explanation: 'write 는 일단 buffer(page cache)에 쓰고 나중에 flusher 가 반영한다. 즉시 보장이 필요하면 fsync(fd).',
    },
    {
      id: 'ch25-tf-8',
      type: 'true-false',
      prompt: 'rename() 은 atomic 해서, 도중에 crash 가 나도 파일 이름은 옛 이름이거나 새 이름이지 중간 상태가 되지 않는다.',
      answer: true,
      explanation: '에디터의 안전 저장 패턴(tmp + fsync + rename)이 이 성질에 기댄다.',
    },
    {
      id: 'ch25-tf-9',
      type: 'true-false',
      prompt: 'rm 으로 hard link 가 3개인 파일의 이름 하나를 지우면, 파일 데이터도 즉시 삭제된다.',
      answer: false,
      explanation: 'rm = unlink — 이름과 inode 의 연결 하나를 끊고 link count 를 줄일 뿐. count 가 0 이 되어야 inode/data 가 해제된다.',
    },
    {
      id: 'ch25-tf-10',
      type: 'true-false',
      prompt: 'symbolic link 는 원본과 같은 inode 를 공유한다.',
      answer: false,
      explanation: '그건 hard link. symlink 는 자기 자신의 inode 를 가진 별도 파일로, 내용은 대상 "경로 문자열" 이다.',
    },
    {
      id: 'ch25-tf-11',
      type: 'true-false',
      prompt: 'hard link 생성 직후의 원본(file)과 새 이름(file2)은 본질적으로 차이가 없는 동등한 이름이다.',
      answer: true,
      explanation: '둘 다 같은 inode 를 가리키는 directory entry 일 뿐 — 어느 쪽이 "원본" 인지 구분 자체가 없다.',
    },
    {
      id: 'ch25-tf-12',
      type: 'true-false',
      prompt: '디렉터리는 일반 read() 대신 opendir/readdir/closedir 전용 인터페이스로 읽는다.',
      answer: true,
      explanation: '디렉터리는 구조(entry 포맷)가 정해져 있어 전용 API 를 쓴다. readdir 가 NULL 을 반환하면 끝.',
    },

    // ═══════════════════════════════════════════════════════════════════
    // 객관식
    // ═══════════════════════════════════════════════════════════════════
    {
      id: 'ch25-mc-1',
      type: 'multiple-choice',
      prompt: '새로 open 한 파일이 fd 3 을 받는 이유로 가장 정확한 것은?',
      options: [
        { text: '3 이 행운의 숫자라서 관례적으로 사용한다' },
        { text: '0/1/2 는 stdin/stdout/stderr 가 차지하고 있고, fd 는 "가장 작은 빈 칸" 에 할당되기 때문' },
        { text: 'fd 는 항상 3 부터 시작하도록 POSIX 가 강제하기 때문' },
        { text: '커널이 무작위로 할당했는데 우연히 3 이 나온 것' },
      ],
      answerIndex: 1,
      explanation: '가장 작은 빈 fd 규칙. 이 규칙이 close(1) 후 open 으로 redirection 을 구현하는 비밀이기도 하다.',
    },
    {
      id: 'ch25-mc-2',
      type: 'multiple-choice',
      prompt: 'offset 이 저장되는 위치는?',
      options: [
        { text: 'on-disk inode 안' },
        { text: '프로세스의 fd table 안' },
        { text: 'open file table entry (struct file) 안' },
        { text: '사용자 버퍼 안' },
      ],
      answerIndex: 2,
      explanation: 'offset 은 "파일을 열었을 때" 생기는 정보이므로 open file entry 에 산다. 파일 자체의 metadata(크기·권한·링크 수)는 inode 에.',
    },
    {
      id: 'ch25-mc-3',
      type: 'multiple-choice',
      prompt: 'stat() 이 보여주는 정보(크기, link count, inode 번호 등)의 출처는?',
      options: [
        { text: 'open file table entry' },
        { text: 'inode' },
        { text: '디렉터리 entry' },
        { text: '프로세스의 PCB' },
      ],
      answerIndex: 1,
      explanation: '커널이 디렉터리에서 이름을 찾아 inode 에 도달한 뒤, inode 의 metadata 를 user space 의 struct stat 변수로 복사해 준다.',
    },
    {
      id: 'ch25-mc-4',
      type: 'multiple-choice',
      prompt: 'echo hello > foo 와 echo hello >> foo 의 open 플래그 차이는?',
      options: [
        { text: '> 는 O_APPEND, >> 는 O_TRUNC' },
        { text: '> 는 O_TRUNC (기존 내용 비움), >> 는 O_APPEND (끝에 추가)' },
        { text: '둘 다 O_TRUNC 이고 동작이 같다' },
        { text: '> 는 O_RDONLY, >> 는 O_WRONLY' },
      ],
      answerIndex: 1,
      explanation: '덮어쓰기는 O_CREAT|O_WRONLY|O_TRUNC, 추가는 O_CREAT|O_WRONLY|O_APPEND.',
    },
    {
      id: 'ch25-mc-5',
      type: 'multiple-choice',
      prompt: '새 파일을 만들어 쓴 뒤 fsync(fd) 까지 했는데도 fsync(dirfd) 가 추가로 필요할 수 있는 이유는?',
      options: [
        { text: 'fsync 는 한 번에 절반만 반영하기 때문' },
        { text: '"foo 라는 이름이 존재한다" 는 정보(디렉터리 entry)는 파일이 아니라 부모 디렉터리의 데이터에 있기 때문' },
        { text: 'dirfd 를 fsync 해야 fd 의 fsync 가 활성화되기 때문' },
        { text: '디렉터리는 캐시되지 않기 때문' },
      ],
      answerIndex: 1,
      explanation: '내용은 디스크에 있는데 이름이 없는 상태로 crash 날 수 있다 — 이름의 존재는 디렉터리 fsync 로 보장.',
    },
    {
      id: 'ch25-mc-6',
      type: 'multiple-choice',
      prompt: '에디터의 안전 저장 패턴의 올바른 순서는?',
      options: [
        { text: 'rename → write → fsync → close' },
        { text: 'tmp 파일 open → write → fsync → close → rename' },
        { text: '원본 open → O_TRUNC → write → fsync' },
        { text: 'unlink(원본) → tmp 생성 → write → rename' },
      ],
      answerIndex: 1,
      explanation: '임시 파일에 완성본을 만들어 디스크 반영까지 확인한 뒤 atomic rename 으로 교체 — 어느 시점에 crash 가 나도 원본은 완전한 버전.',
    },
    {
      id: 'ch25-mc-7',
      type: 'multiple-choice',
      prompt: 'hard link 생성(ln file file2)이 일반적인 파일 생성과 다른 점은?',
      options: [
        { text: '디렉터리에 이름을 넣지 않는다' },
        { text: '새 inode 를 만들지 않고, 기존 inode 에 새 이름만 추가한다' },
        { text: '데이터 블록을 복사한다' },
        { text: '권한 설정을 건너뛴다' },
      ],
      answerIndex: 1,
      explanation: '파일 생성의 Step 1(inode 생성)을 생략 — 기존 inode 의 link count 만 +1 되고 directory entry 가 추가된다.',
    },
    {
      id: 'ch25-mc-8',
      type: 'multiple-choice',
      prompt: 'symbolic link 가 hard link 와 달리 가능한 것 두 가지의 올바른 조합은?',
      options: [
        { text: '같은 inode 공유 / 데이터 자동 복제' },
        { text: '디렉터리 가리키기 / 다른 파일 시스템 가리키기' },
        { text: '원본 삭제 후에도 데이터 접근 / link count 증가' },
        { text: 'offset 공유 / fd 공유' },
      ],
      answerIndex: 1,
      explanation: '경로 "문자열" 을 저장하므로 경계를 넘을 수 있다. 대신 원본이 사라지면 dangling reference.',
    },
    {
      id: 'ch25-mc-9',
      type: 'multiple-choice',
      prompt: 'struct dirent 의 필드 설명으로 틀린 것은?',
      options: [
        { text: 'd_ino — 이 entry 의 inode 번호' },
        { text: 'd_off — 다음 directory entry 로 가기 위한 offset' },
        { text: 'd_reclen — 이 record 의 길이 (이름 길이에 따라 달라짐)' },
        { text: 'd_type — 파일 내용의 MIME 타입 (text/html 등)' },
      ],
      answerIndex: 3,
      explanation: 'd_type 은 DT_REG(일반 파일)/DT_DIR(디렉터리)/DT_LNK(symlink) 같은 파일 종류이지 MIME 타입이 아니다.',
    },

    // ═══════════════════════════════════════════════════════════════════
    // 단답형 — 트레이스 계산
    // ═══════════════════════════════════════════════════════════════════
    {
      id: 'ch25-sa-1',
      type: 'short-answer',
      prompt: 'open 직후 read(fd, buf, 100) 을 세 번 호출해 모두 100 을 반환받았다. 현재 offset 은? (정수)',
      answers: ['300'],
      hint: 'read 마다 offset 자동 증가',
      explanation: '0 → 100 → 200 → 300. 네 번째 read 가 0 을 반환하면 EOF (offset 은 300 그대로).',
    },
    {
      id: 'ch25-sa-2',
      type: 'short-answer',
      prompt: 'open 직후 lseek(fd, 200, SEEK_SET) 후 read(fd, buf, 50) 이 50 을 반환했다. 현재 offset 은? (정수)',
      answers: ['250'],
      hint: 'lseek 로 200, read 로 +50',
      explanation: 'SEEK_SET 은 파일 시작 기준 — 200 으로 점프 후 50 읽어 250.',
    },
    {
      id: 'ch25-sa-3',
      type: 'short-answer',
      prompt: 'echo hello > file 후 ln file file2, ln file2 file3 을 실행했다. stat file 의 Links 값은? (정수)',
      answers: ['3'],
      hint: '이름이 몇 개인가',
      explanation: 'file·file2·file3 세 이름이 같은 inode 를 가리킴 → link count 3.',
    },
    {
      id: 'ch25-sa-4',
      type: 'short-answer',
      prompt: '위 상태에서 rm file 을 실행하면 stat file2 의 Links 값은? (정수)',
      answers: ['2'],
      hint: 'unlink 는 count 를 1 줄인다',
      explanation: '이름 하나가 끊겨 3 → 2. 데이터는 그대로 — count 0 이 되어야 해제.',
    },
    {
      id: 'ch25-sa-5',
      type: 'short-answer',
      prompt: 'ln -s file file2 로 만든 symlink file2 의 ls -al 크기(byte)는? (정수)',
      answers: ['4'],
      hint: 'symlink 의 내용 = 대상 경로 문자열',
      explanation: '"file" 4글자를 내용으로 저장하므로 크기 4. 대상 경로가 길수록 커진다.',
    },
    {
      id: 'ch25-sa-6',
      type: 'short-answer',
      prompt: 'rm 명령이 내부적으로 호출하는 시스템 콜의 이름은? (영문)',
      answers: ['unlink', 'unlink()'],
      hint: 'strace rm foo 로 확인 가능',
      explanation: '파일 삭제 = 이름과 inode 사이의 link 를 제거하는 unlink.',
    },
    {
      id: 'ch25-sa-7',
      type: 'short-answer',
      prompt: 'symlink 가 가리키던 원본이 삭제되어 경로가 허공을 가리키게 된 상황을 부르는 용어는? (영문)',
      answers: ['dangling reference', 'dangling', 'danglingreference'],
      hint: 'cat file2 → No such file or directory',
      explanation: 'dangling reference — symlink 파일 자체는 남아 있지만 대상 경로가 사라진 상태.',
    },

    // ═══════════════════════════════════════════════════════════════════
    // 코드 빈칸
    // ═══════════════════════════════════════════════════════════════════
    {
      id: 'ch25-cb-1',
      type: 'code-blank',
      prompt: 'strace cat foo 의 출력 — 빈칸(반환값)을 채워라. (foo 의 내용은 "hello\\n" 6바이트)',
      language: 'text',
      segments: [
        { kind: 'text', text: 'open("foo", O_RDONLY|O_LARGEFILE) = ' },
        { kind: 'blank', answers: ['3'], width: 4 },
        { kind: 'text', text: '   // 0/1/2 다음의 가장 작은 빈 칸\nread(3, "hello\\n", 4096)          = ' },
        { kind: 'blank', answers: ['6'], width: 4 },
        { kind: 'text', text: '   // 실제 읽은 byte 수\nwrite(' },
        { kind: 'blank', answers: ['1'], width: 3 },
        { kind: 'text', text: ', "hello\\n", 6)            = 6   // stdout 으로 출력\nread(3, "", 4096)                 = ' },
        { kind: 'blank', answers: ['0'], width: 4 },
        { kind: 'text', text: '   // EOF\nclose(3)                          = 0' },
      ],
      explanation: 'open→3(최소 빈 fd), read→6(요청 4096 이지만 실제 6), write 대상은 fd 1(stdout), 두 번째 read→0(EOF).',
    },
    {
      id: 'ch25-cb-2',
      type: 'code-blank',
      prompt: '파일 생성 open 호출 — 빈칸(플래그)을 채워라. ("없으면 생성 + 쓰기 전용 + 있으면 비우기")',
      language: 'c',
      segments: [
        { kind: 'text', text: 'int fd = open("foo", ' },
        { kind: 'blank', answers: ['O_CREAT'], width: 9 },
        { kind: 'text', text: ' | O_WRONLY | ' },
        { kind: 'blank', answers: ['O_TRUNC'], width: 9 },
        { kind: 'text', text: ', S_IRUSR | S_IWUSR);\n\n// append 버전 (>> redirection):\nint fd2 = open("foo", O_CREAT | O_WRONLY | ' },
        { kind: 'blank', answers: ['O_APPEND'], width: 10 },
        { kind: 'text', text: ', mode);' },
      ],
      explanation: 'O_CREAT(없으면 생성) + O_TRUNC(있으면 크기 0) vs O_APPEND(끝에 추가). S_IRUSR|S_IWUSR 는 생성 시 소유자 읽기/쓰기 권한.',
    },
    {
      id: 'ch25-cb-3',
      type: 'code-blank',
      prompt: '안전 저장 패턴 — 빈칸을 채워라.',
      language: 'c',
      segments: [
        { kind: 'text', text: 'int fd = open("foo.txt.tmp", O_WRONLY | O_CREAT | O_TRUNC);\nwrite(fd, buffer, size);     // 새 버전을 임시 파일에\n' },
        { kind: 'blank', answers: ['fsync(fd)', 'fsync(fd);'], width: 12 },
        { kind: 'text', text: ';                  // 디스크 반영 보장\nclose(fd);\n' },
        { kind: 'blank', answers: ['rename("foo.txt.tmp", "foo.txt")', 'rename("foo.txt.tmp", "foo.txt");'], width: 36 },
        { kind: 'text', text: ';   // atomic 교체' },
      ],
      explanation: 'fsync 로 내용을 디스크에 박은 뒤 rename 으로 한 번에 교체 — crash 가 나도 옛 버전 아니면 새 버전.',
    },
    {
      id: 'ch25-cb-4',
      type: 'code-blank',
      prompt: 'fork-seek 예제 — 실행 결과를 채워라.',
      language: 'c',
      segments: [
        { kind: 'text', text: 'int fd = open("file.txt", O_RDONLY);\nint rc = fork();\nif (rc == 0) {\n    rc = lseek(fd, 10, SEEK_SET);\n    printf("child: offset %d\\n", rc);\n} else if (rc > 0) {\n    (void) wait(NULL);\n    printf("parent: offset %d\\n", (int) lseek(fd, 0, SEEK_CUR));\n}\n\n// 출력:\n// child: offset ' },
        { kind: 'blank', answers: ['10'], width: 4 },
        { kind: 'text', text: '\n// parent: offset ' },
        { kind: 'blank', answers: ['10'], width: 4 },
      ],
      explanation: 'fork 로 같은 open file entry 를 공유하므로 자식의 lseek(10) 이 부모에게도 보인다 — 둘 다 10.',
    },
    {
      id: 'ch25-cb-5',
      type: 'code-blank',
      prompt: '디렉터리 읽기 코드 — 빈칸을 채워라.',
      language: 'c',
      segments: [
        { kind: 'text', text: 'int main(int argc, char *argv[]) {\n    DIR *dp = ' },
        { kind: 'blank', answers: ['opendir(".")', 'opendir(".");'], width: 14 },
        { kind: 'text', text: ';\n    assert(dp != NULL);\n    struct dirent *d;\n    while ((d = ' },
        { kind: 'blank', answers: ['readdir(dp)', 'readdir(dp);'], width: 13 },
        { kind: 'text', text: ') != ' },
        { kind: 'blank', answers: ['NULL', 'null'], width: 6 },
        { kind: 'text', text: ') {\n        printf("%d %s\\n", (int) d->d_ino, d->d_name);\n    }\n    closedir(dp);\n    return 0;\n}' },
      ],
      explanation: 'opendir → readdir 를 NULL 까지 반복 → closedir. 출력은 ls -i 와 비슷하게 inode 번호 + 이름.',
    },
    {
      id: 'ch25-cb-6',
      type: 'code-blank',
      prompt: 'hard link 트레이스 — 빈칸(Links 값)을 채워라.',
      language: 'text',
      segments: [
        { kind: 'text', text: 'echo hello > file     →  Links: 1\nln file file2         →  Links: ' },
        { kind: 'blank', answers: ['2'], width: 3 },
        { kind: 'text', text: '\nln file2 file3        →  Links: ' },
        { kind: 'blank', answers: ['3'], width: 3 },
        { kind: 'text', text: '\nrm file               →  Links: ' },
        { kind: 'blank', answers: ['2'], width: 3 },
        { kind: 'text', text: '\nrm file2              →  Links: 1\nrm file3              →  Links: ' },
        { kind: 'blank', answers: ['0'], width: 3 },
        { kind: 'text', text: '  → inode/data block 해제 가능' },
      ],
      explanation: 'ln 마다 +1, rm(unlink) 마다 -1. 0 이 되어야 실제 데이터가 삭제될 수 있다.',
    },

    // ═══════════════════════════════════════════════════════════════════
    // 서술형
    // ═══════════════════════════════════════════════════════════════════
    {
      id: 'ch25-essay-1',
      type: 'essay',
      prompt:
        'read(3, buf, 4096) 한 줄이 처리되는 과정을 user space 에서 디스크까지 단계별로 서술하라. (fd table, open file entry, inode 가 각각 어떤 역할을 하는지 포함)',
      modelAnswer: [
        '1. 사용자가 fd 3 을 넘기며 read 를 호출 → system call 로 커널 모드 진입.',
        '2. 커널이 현재 프로세스의 fd table[3] 을 본다 — fd 는 프로세스별 정수 인덱스일 뿐이다.',
        '3. 거기 저장된 포인터로 open file table entry(struct file)를 찾는다. entry 에는 ref count, 읽기/쓰기 가능 여부, 현재 offset, inode 포인터가 있다.',
        '4. entry 의 offset 으로 "파일의 어디서부터 읽을지" 를 정하고, inode 포인터를 따라간다.',
        '5. inode(metadata)를 통해 실제 데이터 블록의 위치를 알아낸다.',
        '6. 디스크(또는 이미 캐시되어 있다면 page cache)에서 해당 데이터를 읽는다.',
        '7. 읽은 내용을 user buffer(buf)로 복사한다.',
        '8. struct file 의 offset 을 읽은 byte 수만큼 증가시키고, 읽은 byte 수를 반환한다 (0 이면 EOF).',
        '',
        '역할 정리: fd table = 프로세스별 "정수 → entry" 매핑 / open file entry = 열림 상태(offset 등)의 보관소 / inode = 파일 자체의 metadata 와 데이터 위치. stat() 이 보는 곳은 inode, read 가 갱신하는 곳은 entry 의 offset 이다.',
      ].join('\n'),
      rubric: [
        'fd table → struct file → inode → data block 의 사슬 순서',
        'offset 이 entry 에 있고 read 후 증가한다는 점',
        'inode 가 metadata/블록 위치 제공이라는 점',
      ],
    },
    {
      id: 'ch25-essay-2',
      type: 'essay',
      prompt: 'hard link 와 symbolic link 의 차이를 inode 관점에서 설명하고, 원본 삭제 시 각각 어떤 일이 일어나는지 서술하라.',
      modelAnswer: [
        '[Hard link] ln file file2 는 새 inode 를 만들지 않는다. 기존 inode 에 "file2" 라는 directory entry 를 하나 더 연결하고 link count 를 +1 할 뿐이다. 그래서 file 과 file2 는 같은 inode 번호를 갖는 완전히 동등한 이름이며, 원본/사본 구분이 없다. 제한: inode 번호는 파일 시스템 내부에서만 유일하므로 다른 파일 시스템으로 만들 수 없고, cycle 방지를 위해 디렉터리에는 일반적으로 만들 수 없다.',
        '',
        '[Symbolic link] ln -s file file2 는 자기 자신의 inode 를 가진 "별도의 파일" 을 만든다. 그 내용은 데이터가 아니라 대상의 경로 문자열("file", 4바이트)이다. 경로 문자열이므로 다른 파일 시스템·디렉터리도 가리킬 수 있다.',
        '',
        '[원본 삭제 시] hard link: rm file 은 unlink — link count 가 2→1 로 줄 뿐 데이터는 남고, file2 로 계속 접근 가능하다. count 가 0 이 되어야 inode/data 가 해제된다. symbolic link: rm file 후에도 file2 (link 파일) 자체는 남지만, 가리키는 경로 "file" 이 사라졌으므로 cat file2 는 No such file or directory — dangling reference 가 된다.',
      ].join('\n'),
      rubric: [
        'hard link = 같은 inode 에 이름 추가(count+1), symlink = 자기 inode + 경로 문자열',
        'hard link 의 두 제한(파일 시스템 경계, 디렉터리)과 이유',
        '원본 삭제 시: count 감소로 데이터 유지 vs dangling reference',
      ],
    },
  ],
};

export default quiz;
