import { Callout } from './components/Callout/Callout';
import { MdxPre } from './components/CodeBlock/CodeBlock';
import { ProblemSolution } from './components/ProblemSolution/ProblemSolution';
import { Figure } from './components/Figure/Figure';
import {
  MemorySwapLayout,
  PageMovement,
  ValidPresentMatrix,
  PageFaultTrapFlow,
  ReplacementSteps,
  LazyApproachFlow,
  MemoryFullCycle,
  WatermarkDaemonFlow,
  RetryInstructionFlow,
  TlbHitMissFlow,
  SystemComponentPipeline,
  PageDaemonScenarios,
  PfnReassignment,
  FullFlowSteps,
  FaultDecisionLevels,
  BackingStoreBranch,
} from './components/Ch15Diagrams/Ch15Diagrams';
import {
  AmatComparison,
  ReplacementTrace,
  BeladyAnomalyChart,
  WorkloadNoLocality,
  Workload8020,
  WorkloadLooping,
  ClockAlgorithm,
  DirtyBitDecision,
  ThrashingChart,
  PrefetchClustering,
  PolicyVsDaemon,
} from './components/Ch16Diagrams/Ch16Diagrams';
import {
  VmThreadLayoutLinux,
  TaskStructSharing,
  StackFrameZoom,
} from './components/Ch18Diagrams/Ch18Diagrams';
import {
  PthreadJoinTimeline,
  StackReturnDanger,
  LockVariantsComparison,
  CondVarProtocol,
} from './components/Ch19Diagrams/Ch19Diagrams';
import {
  AtomicityRaceTimeline,
  TestAndSetMechanic,
  CasVsTas,
  TicketLockFlow,
  LostWakeupRace,
  FutexFastSlowPath,
  TwoPhaseLock,
} from './components/Ch20Diagrams/Ch20Diagrams';
import {
  CounterContention,
  PerfectVsActualScaling,
  ApproximateCounterArch,
  ApproximateCounterExample,
  ThresholdTradeoff,
  ListSingleLockBottleneck,
  HandOverHandLocking,
  MichaelScottQueueLayout,
  QueueDequeueDummyShift,
  ConcurrentHashTable,
  HashFunctionDistribution,
} from './components/Ch21Diagrams/Ch21Diagrams';
import {
  CpuVirtTimeline,
  ThreadAnatomy,
  ThreadMemoryMap,
  AddressSpaceLayout,
  MulticoreParallelism,
  IOOverlapTimeline,
  IpcVsThreadSharing,
  RaceConditionTimeline,
  LockCriticalSection,
  DeadlockCycle,
  ThreadVsProcessSwitchDiagram,
} from './components/Ch17Diagrams/Ch17Diagrams';

// MDXProvider accepts a loose components map; casting via `unknown` keeps it flexible
// without pulling in MDX's generic component types.
export const mdxComponents = {
  Callout,
  ProblemSolution,
  Figure,
  pre: MdxPre,
  // 15장(Swapping Mechanisms) 전용 SVG 다이어그램들. 본문에서 컴포넌트로 직접 사용.
  MemorySwapLayout,
  PageMovement,
  ValidPresentMatrix,
  PageFaultTrapFlow,
  ReplacementSteps,
  LazyApproachFlow,
  MemoryFullCycle,
  WatermarkDaemonFlow,
  RetryInstructionFlow,
  TlbHitMissFlow,
  SystemComponentPipeline,
  PageDaemonScenarios,
  PfnReassignment,
  FullFlowSteps,
  FaultDecisionLevels,
  BackingStoreBranch,
  // 16장(Swapping Policies) 전용 SVG 다이어그램들.
  AmatComparison,
  ReplacementTrace,
  BeladyAnomalyChart,
  WorkloadNoLocality,
  Workload8020,
  WorkloadLooping,
  ClockAlgorithm,
  DirtyBitDecision,
  ThrashingChart,
  PrefetchClustering,
  PolicyVsDaemon,
  // 18장 후반(Linux 구현 관점) 전용 SVG.
  VmThreadLayoutLinux,
  TaskStructSharing,
  StackFrameZoom,
  // 19장(Thread API) 전용 SVG.
  PthreadJoinTimeline,
  StackReturnDanger,
  LockVariantsComparison,
  CondVarProtocol,
  // 20장(Locks) 전용 SVG.
  AtomicityRaceTimeline,
  TestAndSetMechanic,
  CasVsTas,
  TicketLockFlow,
  LostWakeupRace,
  FutexFastSlowPath,
  TwoPhaseLock,
  // 21장(Lock-based Concurrent Data Structures) 전용 SVG.
  CounterContention,
  PerfectVsActualScaling,
  ApproximateCounterArch,
  ApproximateCounterExample,
  ThresholdTradeoff,
  ListSingleLockBottleneck,
  HandOverHandLocking,
  MichaelScottQueueLayout,
  QueueDequeueDummyShift,
  ConcurrentHashTable,
  HashFunctionDistribution,
  // 18장 본문(Threads & Concurrency) 전용 SVG 다이어그램들.
  CpuVirtTimeline,
  ThreadAnatomy,
  ThreadMemoryMap,
  AddressSpaceLayout,
  MulticoreParallelism,
  IOOverlapTimeline,
  IpcVsThreadSharing,
  RaceConditionTimeline,
  LockCriticalSection,
  DeadlockCycle,
  ThreadVsProcessSwitchDiagram,
} as unknown as Record<string, React.ComponentType<unknown>>;
